### ISSUE TITLE
Unable to use NW-A46 touch screen after disabling by accident

### ISSUE THREAD

**Issue by ghost** [unknown321/wampy#50]
In the process of trying to correct an error with my settings in wampy (Couldn't save adjusted walkman one settings via the wampy menu after the prompted reboot),I attempted to wipe wampy for a complete reinstall,but foolishly locked the screen in the misc settings page before doing so, and am now completely unable to switch into wampy to toggle off the screen lock(I suspect I may have erased a settings file on the mr walkman hardware I use too)  I tried to uninstall and reinstall wampy via the windows exe but had no luck, even though the program indicated it was sucessful, the screen remains locked.

 Can anything be done or is the device bricked/soft locked? I would factory reset the device but cannot acess the menu to do so.

**Comment by unknown321** [comment]
Have you read the documentation?

> `Disable touchscreen` disables touchscreen on next Wampy toggle. To temporarily enable touchscreen in Wampy while in this mode, set volume to 120 in default player app and toggle Wampy on.

https://github.com/unknown321/wampy/blob/master/USAGE.md#misc

You can also edit the config file on your pc to disable that option.

**Comment by VisualWarlock** [comment]
I've just tried what you suggested, unfortunately toggling after setting the volume to 120 only seems to bring up the "touch  panel disabled hold switch to enable it" message.

**Comment by unknown321** [comment]
Reinstalling will not turn the touchscreen on, you need to edit config file on the device from your PC (or use 120 volume method). There is also `upgrade.log` on the device which has installation details.

**Comment by VisualWarlock** [comment]
Ah I see, so finding the correct part of the config file, located in the wampy folder on the device and changing the screen setting then? 

Thanks for your help by the way, I've been loving your software I just got a bit carried away in tweaking the settings, hopefully I can get it going again with your assistance!

**Comment by unknown321** [comment]
> Ah I see, so finding the correct part of the config file, located in the wampy folder on the device and changing the screen setting then?

Correct, `[featured] -> touchscreenstaysoff = 0`

Speaking of 120 volume method, it won't work if "Limit max volume" option is on. This is a bug, will fix it some time later.

**Comment by unknown321** [comment]
> > Ah I see, so finding the correct part of the config file, located in the wampy folder on the device and changing the screen setting then?
> 
> Correct, `[featured] -> touchscreenstaysoff = 0`
> 
> Speaking of 120 volume method, it won't work if "Limit max volume" option is on. This is a bug, will fix it some time later.

Fixed in v1.10.3.

I've also removed "Urgent" from this issue. Urgent means that people are dying, mp3 player malfunction is not urgent at all.

**Comment by VisualWarlock** [comment]
> > > Ah I see, so finding the correct part of the config file, located in the wampy folder on the device and changing the screen setting then?
> > 
> > 
> > Correct, `[featured] -> touchscreenstaysoff = 0`
> > Speaking of 120 volume method, it won't work if "Limit max volume" option is on. This is a bug, will fix it some time later.
> 
> Fixed in v1.10.3.
> 
> I've also removed "Urgent" from this issue. Urgent means that people are dying, mp3 player malfunction is not urgent at all.

Fair, urgent is a bit hyperbolic on my part. Unfortunately I can't adjust the config because the wampy folder isn't appearing on my device after completing the fresh Installation.

**Comment by VisualWarlock** [comment]
![Image](https://github.com/user-attachments/assets/6d2b6fd7-bca3-4be7-b3fc-9937a41daa9a)

**Comment by unknown321** [comment]
> ![Image](https://github.com/user-attachments/assets/6d2b6fd7-bca3-4be7-b3fc-9937a41daa9a)

And `upgrade.log` from the device?

**Comment by VisualWarlock** [comment]
Strangely I still can't install wampy itself. I used the latest windows installer (your most recent update), and still not luck. Its possible I might be selecting the wrong option from the Installer.

I have an NW40 series player with the NW walkman one NW40  software installed, just to double check which option should I select during Installation?  

I have noticed a userdata.tar folder from wampy, (no main wampy folder though) do I need to run the uninstaller to remove it?

**Comment by VisualWarlock** [comment]
Still no luck

**Comment by VisualWarlock** [comment]
> > Trying to use the linux install, but opening the scistool on my system doesn't do anything, is it ARCH compatible? I downloaded the file from the linked website in the guide. I also tried running the command in terminal.
> 
> Did you ran it as root? Any logs?

Ah I see what I  did wrong, the tool opens fine.

**Comment by VisualWarlock** [comment]
> > Update, I can open the tool fine but using the " scsitool list_devices" with sudo (root permission) doesn't work
> 
> No idea, works on my machine.
> 
> $ sudo scsitool-amd64 list_devices
> Sony device(s) found:
> No devices found.

I feel like I'm missing something obvious. I enabled the scsitool to run by right clicking and opening in Konsole (weirdly other terminals apps wouldn't open it), but none of the commands work even with sudo as prefix, not just the list_devices option.

**Comment by VisualWarlock** [comment]
I've attached the upgrade log

[upgrade.log](https://github.com/user-attachments/files/23409314/upgrade.log)

**Comment by unknown321** [comment]
> Still no luck, to be clear, laying it out in idiot proof terms, if I have a 40 series walkman with the mr Walkman NW40 series Walkman One software installed, in windows I need to

Correct.

> OR with Linux:
> 
>     1. copy and paste the relevant NW_WM_FW.UPG file for the NW40 series to the root directory prior to installation

Try both A40 and WalkmanOne upg files, I don't remember the difference between them and how will they interact with your setup. 

>     5. run the following command scsitool -d -s nw-a50 /dev/sg4 do_fw_upgrade

With device from step 4.

Upgrade.log is from `Mon Oct 13 18:34:39 UTC 2025` - upgrade never happened past that date, meaning that you were supplying wrong upgrade file or not getting into upgrade mode at all.

**Comment by unknown321** [comment]
> Its hard to tell if either UPG file is making a difference because I still can't run the scsitool command.

You can try run it on windows. Maybe you are missing some system libs on your arch installation.

**Comment by VisualWarlock** [comment]
> > Its hard to tell if either UPG file is making a difference because I still can't run the scsitool command.
> 
> You can try run it on windows. Maybe you are missing some system libs on your arch installation.

Its possible, I'm not sure what its packages and dependecies are on Arch, I'll try running it the windows version too, as you've suggested.

**Comment by VisualWarlock** [comment]
Tried removing Mr walkman, resetting the device to factory settings, reinstalling it, and then the A50 version of your software still experiencing the same issue. I also tried the windows scsitool executeable, but it was deleted by windows due to an error.

**Comment by unknown321** [comment]
> , but it was deleted by windows due to an error.

What do you mean?

**Comment by VisualWarlock** [comment]
> Use [google lens](https://lens.google/) to translate the error. Looks like windows deletes scsitool for some reason.

Will do, incidentally, does the windows version of scsitool perform the update automatically or does it still require manually inputting commands in the windows terminal?

**Comment by VisualWarlock** [comment]
Hi, thanks for all your help, I've been busy so I put the device aside for awhile, and I actually ended up picking up a new player, so I might be giving the the Walkman to someone else as a gift. feel free to close the thread if you like, or leave it open.

thanks again!
